version: "3.9"

services:
  app:
    container_name: tienda_app
    build: .
    volumes:
      - ./:/app
      - ./data:/data
    working_dir: /app
    depends_on:
      - sqlite
    tty: true
    stdin_open: true


  sqlite:
    container_name: tienda_sqlite
    image: keinos/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    working_dir: /data
